test_anagram (__main__.TestExercice) ... FAIL
test_doubles (__main__.TestExercice) ... ERROR
test_frequence (__main__.TestExercice) ... ERROR
test_grades (__main__.TestExercice) ... ok
test_order (__main__.TestExercice) ... ok

======================================================================
ERROR: test_doubles (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 49, in test_doubles
    output = [exercice.contains_doubles(v) for v in values]
  File "test_exercice.py", line 49, in <listcomp>
    output = [exercice.contains_doubles(v) for v in values]
  File "/home/runner/work/c04-ch6-exercices-kaelhc/c04-ch6-exercices-kaelhc/exercice.py", line 29, in contains_doubles
    ensemble =set(list)
TypeError: 'type' object is not iterable

======================================================================
ERROR: test_frequence (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 77, in test_frequence
    output = [exercice.frequence(s) for s in sentences]
  File "test_exercice.py", line 77, in <listcomp>
    output = [exercice.frequence(s) for s in sentences]
  File "/home/runner/work/c04-ch6-exercices-kaelhc/c04-ch6-exercices-kaelhc/exercice.py", line 58, in frequence
    return {frequency[sorted_keys]}
TypeError: unhashable type: 'list'

======================================================================
FAIL: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 40, in test_anagram
    'Erreur dans la vérification de l\'anagramme'
AssertionError: Lists differ: [None, None] != [True, False]

First differing element 0:
None
True

- [None, None]
+ [True, False] : Erreur dans la vérification de l'anagramme

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=2)
